name: Update Workflows

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        run: python scripts/runner.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<your_email>"
          git add workflows.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update workflows.json"
          git push
